// @generated by `cargo run -p pt-cli --bin codegen` — do not edit.
// Mirrors crates/core/src/gpu_layout.rs. See that file for the layout rules.

struct Material {
  base_color   : vec3<f32>,   // offset 0
  metallic     : f32,         // offset 12
  emissive     : vec3<f32>,   // offset 16
  roughness    : f32,         // offset 28
  ior          : f32,         // offset 32
  transmission : f32,         // offset 36
  _pad0        : f32,         // offset 40
  _pad1        : f32,         // offset 44
  // Complex IOR, consulted only when k is non-zero (the conductor flag).
  eta          : vec3<f32>,   // offset 48
  _pad2        : f32,         // offset 60
  k            : vec3<f32>,   // offset 64
  _pad3        : f32,         // offset 76, size 80
};

// A sphere or a parallelogram in one tagged struct. WebGPU guarantees only
// eight storage buffers per stage and this renderer needs all eight, so the two
// analytic primitive types share one buffer. See crates/core/src/gpu_layout.rs.
struct Primitive {
  position : vec3<f32>,       // offset 0   sphere centre / quad origin
  radius   : f32,             // offset 12  sphere only
  edge_u   : vec3<f32>,       // offset 16  quad only
  kind     : u32,             // offset 28
  edge_v   : vec3<f32>,       // offset 32  quad only
  material : u32,             // offset 44
  normal   : vec3<f32>,       // offset 48  quad only
  _pad0    : f32,             // offset 60, size 64
};

const PRIM_KIND_SPHERE: u32 = 0u;
const PRIM_KIND_QUAD: u32 = 1u;

// 48 bytes: radiance and sample count, then the denoiser's guide channels.
// Appended here rather than given their own buffer because the megakernel
// already binds the eight storage buffers WebGPU guarantees per stage.
struct Accum {
  radiance : vec3<f32>,        // offset 0
  samples  : f32,              // offset 12
  albedo   : vec3<f32>,        // offset 16
  depth    : f32,              // offset 28
  normal   : vec3<f32>,        // offset 32
  traversal: f32,              // offset 44
  radiance_sq: vec3<f32>,      // offset 48
  _pad0    : f32,              // offset 60, size 64
};

struct Uniforms {
  cam_origin         : vec3<f32>,  // offset 0
  lens_radius        : f32,        // offset 12
  cam_upper_left     : vec3<f32>,  // offset 16
  focus_distance     : f32,        // offset 28
  cam_horizontal     : vec3<f32>,  // offset 32
  _pad1              : f32,        // offset 44
  cam_vertical       : vec3<f32>,  // offset 48
  _pad2              : f32,        // offset 60
  width              : u32,        // offset 64
  height             : u32,        // offset 68
  sample_offset      : u32,        // offset 72
  samples_per_launch : u32,        // offset 76
  max_depth          : u32,        // offset 80
  frame_seed         : u32,        // offset 84
  num_primitives     : u32,        // offset 88
  num_lights         : u32,        // offset 92
  background         : vec3<f32>,  // offset 96
  num_triangles      : u32,        // offset 108
  num_bvh_nodes      : u32,        // offset 112
  render_mode        : u32,        // offset 116
  sampling_mode      : u32,        // offset 120
  env_width          : u32,        // offset 124
  env_height         : u32,        // offset 128
  env_total_weight   : f32,        // offset 132
  sampler_kind       : u32,        // offset 136
  num_instances      : u32,        // offset 140
  tlas_root          : u32,        // offset 144
  _pad3              : u32,        // offset 148
  _pad4              : u32,        // offset 152
  _pad5              : u32,        // offset 156, size 160
};

// One area light, flattened for direct sampling. A quad and a triangle differ
// only in how the unit square maps onto them, so one struct covers both.
struct Light {
  origin   : vec3<f32>,       // offset 0
  area     : f32,             // offset 12
  edge_u   : vec3<f32>,       // offset 16
  kind     : u32,             // offset 28
  edge_v   : vec3<f32>,       // offset 32
  material : u32,             // offset 44
  normal   : vec3<f32>,       // offset 48
  _pad0    : f32,             // offset 60, size 64
};

const LIGHT_KIND_QUAD: u32 = 0u;
const LIGHT_KIND_TRIANGLE: u32 = 1u;

// --- Wavefront path tracing -------------------------------------------------
//
// In the megakernel all of this lives in registers for a path's lifetime.
// Splitting the tracer into stages means writing it to and reading it from
// global memory at every bounce instead — the architecture's main cost, and why
// PathState is kept to 80 bytes.

struct PathState {
  origin        : vec3<f32>,  // offset 0
  pixel         : u32,        // offset 12
  direction     : vec3<f32>,  // offset 16
  rng_state     : u32,        // offset 28
  throughput    : vec3<f32>,  // offset 32
  prev_bsdf_pdf : f32,        // offset 44
  radiance      : vec3<f32>,  // offset 48
  depth         : u32,        // offset 60
  prev_position : vec3<f32>,  // offset 64
  sampler_dim   : u32,        // offset 76
  guide_albedo  : vec3<f32>,  // offset 80
  guide_depth   : f32,        // offset 92
  guide_normal  : vec3<f32>,  // offset 96
  _pad1         : f32,        // offset 108, size 112
};

struct HitRecord {
  position         : vec3<f32>, // offset 0
  t                : f32,       // offset 12
  normal           : vec3<f32>, // offset 16
  material         : u32,       // offset 28
  geometric_normal : vec3<f32>, // offset 32
  light_area       : f32,       // offset 44
  front_face       : u32,       // offset 48
  valid            : u32,       // offset 52
  _pad0            : u32,       // offset 56
  _pad1            : u32,       // offset 60, size 64
};

// The contribution is computed by SHADE and carried here, so CONNECT only
// answers a visibility question — it never touches a BSDF or a material, which
// is what keeps the occlusion kernel small.
struct ShadowRay {
  origin       : vec3<f32>,  // offset 0
  distance     : f32,        // offset 12
  direction    : vec3<f32>,  // offset 16
  path         : u32,        // offset 28
  contribution : vec3<f32>,  // offset 32
  _pad0        : f32,        // offset 44, size 48
};

// Queue lengths and indirect dispatch arguments in one buffer. The dispatch
// sizes stay on the GPU: a readback between stages would stall for longer than
// the architecture saves. The *_x fields are workgroup counts maintained by
// atomicMax as items are appended, so no pass is needed to turn a count into a
// dispatch size.
// A separate buffer from the counters, and it has to be: WebGPU forbids a
// buffer being both a read-write storage binding and the source of indirect
// arguments within one dispatch, and SHADE writes counters while itself being
// dispatched indirectly.
// Scalar fields, not two vec3: a vec3<u32> has alignment 16, so `shadow` would
// land at offset 16 and the struct would be 48 bytes, while Rust's two [u32; 3]
// put it at 12 in a 32-byte struct. Indirect arguments must be exactly where the
// host says they are.
struct DispatchArgs {
  trace_x  : u32,  // offset 0   workgroups for EXTEND / SHADE
  trace_y  : u32,  // offset 4
  trace_z  : u32,  // offset 8
  shadow_x : u32,  // offset 12  workgroups for CONNECT
  shadow_y : u32,  // offset 16
  shadow_z : u32,  // offset 20
  _pad0    : u32,  // offset 24
  _pad1    : u32,  // offset 28, size 32
};

struct WavefrontCounters {
  next_queue_len : atomic<u32>,  // offset 0
  next_trace_x   : atomic<u32>,  // offset 4
  shadow_len     : atomic<u32>,  // offset 8
  // Snapshot taken by RESET, because it clears the atomic before CONNECT runs.
  shadow_count   : u32,          // offset 12, size 16
};

struct VertexAttr {
  normal : vec3<f32>,         // offset 0
  _pad0  : f32,               // offset 12
  uv     : vec2<f32>,         // offset 16
  _pad1  : vec2<f32>,         // offset 24, size 32
};

struct Triangle {
  i0       : u32,             // offset 0
  i1       : u32,             // offset 4
  i2       : u32,             // offset 8
  material : u32,             // offset 12, size 16
};

// 32 bytes: half a cache line, so a node and its two children span at most two.
// count == 0 means internal, and left_first is the LEFT child index (the right
// child is always left_first + 1). count > 0 means leaf, and left_first is the
// offset into the primitive-index array.
struct BvhNode {
  bounds_min : vec3<f32>,     // offset 0
  left_first : u32,           // offset 12
  bounds_max : vec3<f32>,     // offset 16
  count      : u32,           // offset 28, size 32
};

// Sobol direction numbers, generated by `codegen` from crates/core/src/sobol.rs.
// v[dim][k] is XORed into the running value when bit k of the index is set.
const SOBOL_DIMENSIONS: u32 = 2u;
const SOBOL_BITS: u32 = 32u;
const SOBOL_V: array<array<u32, 32>, 2> = array(
  array<u32, 32>(0x80000000u, 0x40000000u, 0x20000000u, 0x10000000u, 0x08000000u, 0x04000000u, 0x02000000u, 0x01000000u, 0x00800000u, 0x00400000u, 0x00200000u, 0x00100000u, 0x00080000u, 0x00040000u, 0x00020000u, 0x00010000u, 0x00008000u, 0x00004000u, 0x00002000u, 0x00001000u, 0x00000800u, 0x00000400u, 0x00000200u, 0x00000100u, 0x00000080u, 0x00000040u, 0x00000020u, 0x00000010u, 0x00000008u, 0x00000004u, 0x00000002u, 0x00000001u),
  array<u32, 32>(0x80000000u, 0xc0000000u, 0xa0000000u, 0xf0000000u, 0x88000000u, 0xcc000000u, 0xaa000000u, 0xff000000u, 0x80800000u, 0xc0c00000u, 0xa0a00000u, 0xf0f00000u, 0x88880000u, 0xcccc0000u, 0xaaaa0000u, 0xffff0000u, 0x80008000u, 0xc000c000u, 0xa000a000u, 0xf000f000u, 0x88008800u, 0xcc00cc00u, 0xaa00aa00u, 0xff00ff00u, 0x80808080u, 0xc0c0c0c0u, 0xa0a0a0a0u, 0xf0f0f0f0u, 0x88888888u, 0xccccccccu, 0xaaaaaaaau, 0xffffffffu),
);
